### ISSUE TITLE
Conflict With Micronaut Serialization

### ISSUE THREAD

**Issue by SenorPez** [micronaut-projects/micronaut-test-resources#222] opened 2023-04-12 19:16 UTC
### Expected Behavior

Test Resources plugin should be applied and execute containerized databases.

### Actual Behaviour

The following error occurs when attempting to run `startTestResourcesService`

```
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.json.JsonConfiguration] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
```

It was isolated to be due to the configuration change from Micronaut Annotations. Commenting out the following block allows Test Resources to operate correctly:

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("io.micronaut:micronaut-jackson-databind"))
                .using(module("io.micronaut.serde:micronaut-serde-jackson:1.5.2"))
    }
}
```

Of course, that means you're no longer getting the security or benefit from Micronaut Serialization.

### Steps To Reproduce

1. Download the Micronaut Test Resources Demo from here: [https://melix.github.io/blog/2022/08/micronaut-test-resources.html](https://melix.github.io/blog/2022/08/micronaut-test-resources.html).

Direct Link:
[https://github.com/melix/micronaut-test-resources-demo/](https://github.com/melix/micronaut-test-resources-demo/)

You can verify it works out of the box; it does.

2. Add this to the build.gradle.kts:

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("io.micronaut:micronaut-jackson-databind"))
                .using(module("io.micronaut.serde:micronaut-serde-jackson:1.5.2"))
    }
}
```

3. Attempt to run. The following error occurs:
```
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.json.JsonConfiguration] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
```

### Environment Information

Windows
JDK 17

### Version

3.8.8

**Comment by melix** [comment] 2023-07-10 14:38
Closing because it's outdated. The starter templates do not include the substitution anymore and the issue is irrelevant with the upcoming Microanaut 4 release which will not require substitutions.

**Closed by melix** 2023-07-10 14:38 UTC
